### ISSUE TITLE
Feature Request: import config from rclone

### ISSUE THREAD

**Issue by roleohibachi** [bpozdena/OneDriveGUI#102]
I had a dozen or so onedrive remotes configured in rclone. Rclone doesn't do continuous synchronization in the background, it's just an upload/download tool, so I wanted to start using the OneDriveGUI client to perform synchronization. All the data I needed to create my onedrive configs was structured in `~/.config/rclone/rclone.conf` (INI format, with some JSON): name, refresh_token, drive_id. 

OneDriveGUI could add another "import" option on the "Add Profile" screen, which read from an rclone config file, and attempt to create a corresponding onendrive config.

Since OneDriveGUI is a python project, it might be very easy to start with [this simple python script I wrote](https://github.com/roleohibachi/rclone2onedrive/blob/master/rclone2onedrive.py). It reads the rclone config file and spits out shell commands for the onedrive CLI client to be configured. It just needs adapted for the inner workings of OneDriveGUI. The GUI would need another option added for the alternate import source.

I started work on a PR for this, but noticed that there was a "TODO" to refactor profile creation into profile import in some fashion, and I don't want to complicate what you've got in mind for that. Happy to continue, just lmk.

**Comment by bpozdena** [comment]
@roleohibachi , I'm currently not working on anything and I'm not familiar with rclone config structure, so you can go for it :-). 
We would ideally need a single function or class to take care of the conversion. It should just output a valid onedrive config file or configparser object. 
If you can, also please attach some example rclone config file for testing .

I can adjust the GUI part if you're not familiar with pyside.

**Comment by roleohibachi** [comment]
I can do those functions, no problem! I would greatly appreciate your help with the GUI component though. 

Expect a PR and a sample file this evening. Format will be something like:
`def make_config_from_rclone_remote(remote_name: str, rclone_path: str = "~/.config/rclone/rclone.conf") -> tuple[ConfigParser,str]`

Example usage, without GUI parts:
```
(config, refresh_token) = make_config_from_rclone_remote(remote_name = "MyRemoteName", rclone_path = "/optional/path/to/my/rclone.conf")
with open('config', 'w') as configfile:
  config.write(configfile)
with open('refresh_token', 'w' as tokenfile:
  tokenfile.write(refresh_token)
```
