### ISSUE TITLE
Doesn't close when hitting the "x" button, nor is it able to be killed using "Quit" or System Monitor

### ISSUE THREAD

**Issue by aidanhadley** [bpozdena/OneDriveGUI#104]
When trying pressing "x" on the application, it minimizes to the tray. Nothing happens when "Quit" is pressed, or the "onedrive" process is killed in the System Monitor.
Tested on Fedora 38.
Steps to replicate:
1. Open application
2. Press "x"
3. Right-click and Press "Quit"/Hit Alt-F4 or alternative shorcut
4. Go to System Monitor and find "onedrive," then press "End Process"

**Comment by bpozdena** [comment]
Everything is expected behavior. Only when you click on quit, you should see s pop up message asking you if you really want to quit. It's possible the message pops out in the corner of a screen on some distros. Perhaps you missed it?
