### ISSUE TITLE
Is it only possible to download all files locally?

### ISSUE THREAD

**Issue by ph3n92h3** [bpozdena/OneDriveGUI#109]
I don't want to download all the files on OneDrive locally, can this be done? On Windows and MacOS, the official OneDrive software allows files to be downloaded only when they are read or written, and can also be automatically removed from the local after a certain period of time.

**Comment by bpozdena** [comment]
The on-demand feature is not implemented in the client: https://github.com/abraunegg/onedrive#whats-missing
