### ISSUE TITLE
KeyError: 'force_http_11' after distro and software upgrade

### ISSUE THREAD

**Issue by Tippon** [bpozdena/OneDriveGUI#112]
I upgraded Mint from 20.3 to 21.1 today, and followed Abraunegg's directions here:

[https://github.com/abraunegg/onedrive/discussions/2445](https://github.com/abraunegg/onedrive/discussions/2445)

This let me install the latest OneDrive version - 2.4.25 on the updated distro. Initially, OneDriveGUI would run, but OneDrive wouldn't. I followed the instructions here and removed the 'force_http_2' option from the config:

[https://github.com/abraunegg/onedrive/issues/2063](https://github.com/abraunegg/onedrive/issues/2063)

Since doing this, OneDriveGUI has stopped running. I've downloaded the latest version - OneDriveGUI-1.0.2-x86_64.AppImage but have had no luck. I get a long error message containing 'Gtk-Message: 20:28:18.827: Failed to load module "xapp-gtk3-module"' and  ending with 'KeyError: 'force_http_11'. I'll put the full message in a pastebin at the end.

It appears that having that line in the config stops OneDrive from running, but removing it stops OneDriveGUI from running.

Can you help me please?

Pastebin - [https://pastebin.com/cjindmM2](https://pastebin.com/cjindmM2)

EDIT: Sorry, the links were hidden. They should be visible now.

**Comment by abraunegg** [comment]
@Tippon 

In your 'config' file - you should remove:

* force_http_11
* force_http_2

Do not have any of these entries .... unsure why you are even setting them - as you *only* need to play around with those if you are having issues connecting to OneDrive.

Remove them from your 'config' file if present and see how you go.

**Comment by Tippon** [comment]
Apologies for the slow reply.

I had the force_http_2 config entry, but I didn't set it, and it's now been removed. Apart from the initial installation last October, I haven't touched the config file. I've been letting onedrive update with the rest of my system, but the only manual change was when I did the distro upgrade a few weeks ago. I don't have the force_http_11 entry at all.

I just tried running onedrive --synchronize --dry-run from the terminal and it seemed to work as it should, telling me that it would have downloaded a file I edited earlier today. Running OneDriveGUI gave me the same error as in my initial post.

In my /home/tippon/.config/onedrive folder, I have an accounts folder that contains two folders, one named my username and one named my email address. Both of these folders have config files that include the force_http_11 = "false" line, so I've tried removing those separately and running OneDriveGUI each time, but it hasn't changed anything.

This is my current config file:

sync_dir = "/mnt/Storage/OneDrive"
monitor_interval = "300"
log_dir = "/home/tippon/.config/onedrive-gui/"
drive_id = ""
upload_only = "false"
check_nomount = "false"
check_nosync = "false"
download_only = "false"
disable_notifications = "false"
disable_upload_validation = "false"
enable_logging = "true"
local_first = "false"
no_remote_delete = "false"
skip_symlinks = "false"
debug_https = "false"
skip_dotfiles = "false"
dry_run = "false"
min_notify_changes = "5"
monitor_log_frequency = "5"
monitor_fullscan_frequency = "10"
sync_root_files = "false"
classify_as_big_delete = "1000"
user_agent = ""
remove_source_files = "false"
skip_dir_strict_match = "false"
application_id = ""
resync = "false"
bypass_data_preservation = "false"
azure_ad_endpoint = ""
azure_tenant_id = "common"
sync_business_shared_folders = "false"
sync_dir_permissions = "700"
sync_file_permissions = "600"
rate_limit = "125000000"
operation_timeout = "3600"
webhook_enabled = "false"
webhook_public_url = ""
webhook_listening_host = ""
webhook_listening_port = "8888"
webhook_expiration_interval = "86400"
webhook_renewal_interval = "43200"
skip_file = "~*|.~*|*.tmp|desktop.ini"
skip_dir = ""

**Comment by Tippon** [comment]
I just deleted my ~/tippon/.config/onedrive-gui folder and running the same AppImage as before, and it worked. Obviously something in there was causing the issue.

I held off doing it before now in case it helped with troubleshooting, but I couldn't wait any longer. I've kept the folder and the original AppImages for the time being.

**Comment by bpozdena** [comment]
Fixed in AppImage v1.0.3

**Comment by alansenairj** [comment]
It was a little tricky but I got this problem using two accounts. 
I just get this error off when I declare this value was false like this: 

force_http_11 = "false"

Just add this line to your config file and and GUI is started to work. 

ps - using it with Fedora 38 and so on. 


Errors: 

2023-11-02 02:30:55,812 [OneDriveGUI.py:3008][fn=main_window_start_state][INFO] - [GUI] Starting OneDriveGUI maximized
2023-11-02 02:30:55,813 [OneDriveGUI.py:1099][fn=__init__][INFO] - Onedrive_Bussines
2023-11-02 02:30:55,852 [OneDriveGUI.py:1099][fn=__init__][INFO] - my_files
Traceback (most recent call last):
  File "/tmp/.mount_OneDri7t4daf//usr/src/OneDriveGUI.py", line 3114, in <module>
    profile_settings_window = ProfileSettingsWindow()
  File "/tmp/.mount_OneDri7t4daf//usr/src/OneDriveGUI.py", line 1101, in __init__
    self.page = ProfileSettingsPage(profile)
  File "/tmp/.mount_OneDri7t4daf//usr/src/OneDriveGUI.py", line 1224, in __init__
    self.configure_profile_settings_page()
  File "/tmp/.mount_OneDri7t4daf//usr/src/OneDriveGUI.py", line 1489, in configure_profile_settings_page
    self.checkBox_force_http_11.setChecked(self.get_check_box_state("force_http_11"))
  File "/tmp/.mount_OneDri7t4daf//usr/src/OneDriveGUI.py", line 1719, in get_check_box_state
    return self.temp_profile_config["onedrive"][f"{property}"].strip('"') in "true"
KeyError: 'force_http_11'
