### ISSUE TITLE
OneDriveGUI-1.0.3-x86_64.appimage crashes at start

### ISSUE THREAD

**Issue by manolodd** [bpozdena/OneDriveGUI#116]
Good night,

I recently updated to Debian 12 and everything is working right except OneDrive-GUI. I've donwloaded the latest release but the problem remains:

Traceback (most recent call last):
  File "/tmp/user/1000/.mount_OneDriRM8C8N//usr/src/OneDriveGUI.py", line 65, in <module>
    from ui.ui_login import Ui_LoginWindow
  File "/tmp/user/1000/.mount_OneDriRM8C8N/usr/src/ui/ui_login.py", line 18, in <module>
    from PySide6.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PySide6.QtWebEngineWidgets'

I've shown a closed bug https://github.com/bpozdena/OneDriveGUI/issues/59

It is the same problem but with a previous version, just in case it could help.

Thank you.

**Comment by bpozdena** [comment]
It looks like fuse2 in Debian 12 unpacks the appimage into a different location then on other distros. 

I'll try to provide a fix soon. I might get rid of the qtwebengine login method completely. It's really nice when it works, but it unfortunately doesn't on many systems.

In the meantime, you can close onedrivegui and [login from the console](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#authorize-the-application-with-your-onedrive-account) . You might need to specify your config location with '--confdir'.

 Once logged on, you can start the GUI.

**Comment by manolodd** [comment]
Hi,

thank you for your swift answer. I'm currently running onedrive without problem, sync is right, it is correctly authenticated... although it is running from the console which is a bit annoying. Anyway, even running onedrive fine, onedrive-gui still does not work (same problem).

It does not matter. I'll wait for a future version that fix the problem (if possible).

Best regards.

**Comment by bpozdena** [comment]
@manolodd , please try  [OneDriveGUI-1.0.3_fix116-x86_64.AppImage](https://github.com/bpozdena/OneDriveGUI/releases/download/v1.0.3/OneDriveGUI-1.0.3_fix116-x86_64.AppImage) with a potential fix for your issue.

**Comment by manolodd** [comment]
Hey Boris, that's great!!!

I confirm this version runs on my Debian12. Thank you so much

Are you merging this fix to the next release or should I have  to use  the version you have proviedd (OneDriveGUI-1.0.3_fix116-x86_64.AppImage)?

Thank you again, good job!

**Comment by bpozdena** [comment]
Thanks, @manolodd  for the confirmation. Please keep using this AppImage for now. I don't have anything else to release.
