### ISSUE TITLE
Sync is running or Not in GUI when launched

### ISSUE THREAD

**Issue by erenoglu** [bpozdena/OneDriveGUI#119]
I noticed this incoherent information view when I launch OnedriveGUI, one side says sync is not running while other says syncing. In background, it is syncing for sure. Can the main window message be improved a bit for more coherent reflection of sync state?
![image](https://github.com/bpozdena/OneDriveGUI/assets/2230575/de6af47b-6a84-4c58-a5c1-cb9cf377530a)

**Comment by bpozdena** [comment]
@erenoglu  can you please specify the version of your OneDrive client? `onedrive --version`

**Comment by erenoglu** [comment]
hi, it is v2.4.25-1+np1 compiled for Ubuntu using Opensuse build service as advised in onedrive installation wiki

**Comment by noblevirk** [comment]
I'm also having the same issue on Arch Linux, both packages are re-downloaded from AUR repo as of today.

onedrivegui-git 1.0.3.r4.gbc9bf3e-1
onedrive-abraunegg 2.4.25-1

**Comment by bpozdena** [comment]
@noblevirk , can you please share the debug logs? Just start the GUI from terminal and then start sync.

**Comment by bpozdena** [comment]
Fixed in OneDriveGUI v1.1.x
