### ISSUE TITLE
Lot of useless fail notifications when saving certain files

### ISSUE THREAD

**Issue by guillaume-mueller** [bpozdena/OneDriveGUI#124]
When I only had abraunegg/onedrive installed and running, it was syncing my files every n minutes.

Now I have installed OneDriveGUI, sync begins as soon as files changes (hence why I write here). I like this behavior, but when saving certain files or doing a `git commit`, I get a lot of notification saying that some `*.lock` files or whatever failed to sync as they don't exists.

My speculation is that some softwares like git quickly create and delete files for some tasks in my folder. So abraunegg/onedrive or OneDriveGUI detects files changes, knows their path/names then begins sync but don't find them as they don't exists anymore.

Conclusion : I'm not sure I need to be notified that it can't sync files which doesn't exist whatever is the reason why it ever wanted to sync them.

**Comment by bpozdena** [comment]
@guillaume-mueller , the notifications are generated by the client, not the GUI. 

To work around it, you can simply exempt the affected file types or all dot files. Or perhaps all files with .lock extention. You can also exempt .git directories. It really is up to you to filter it out. 

You can also disable the notifications all together under logging tab in the GUI settings window. 

If you have any additional requests regarding the client, please post it on the client's github page. You'll get much better support there.
