### ISSUE TITLE
Only one profile showing up

### ISSUE THREAD

**Issue by ellathewitch** [bpozdena/OneDriveGUI#126]
Hi,

I have 2 accounts and profiles set up through this app. When I open the program through terminal, I can watch it running the updates (once I set it to sync on boot) for my second profile, but the profile itself doesn't show up in the gui. It's not a major issue, but mildly annoying because I can't manually stop or start my second profile. I am running Ubuntu 22.04.3 LTS. I have tried this on 2 different computers with different hardware (one is laptop, one is desktop) both on the same version of Ubuntu, but same result.

**Comment by bpozdena** [comment]
Hi @ellathewitch,

There should be a profile switcher at the top of the main window. Just click on your profile name and a drop-down menu with s list of accounts should show up. 

Can you please provide a screenshot of the GUI. I'm not sure what exactly you can't see there.

**Comment by ellathewitch** [comment]
Oh okay, I see that now. Sorry, I have used a version of this before where each profile was listed on that main screen. I didn't realize there was a profile switcher. I'm all good now.
