### ISSUE TITLE
Minimum python version

### ISSUE THREAD

**Issue by chewblacka** [bpozdena/OneDriveGUI#127]
HI, I'm currently trying to package OneDriveGUI in nix. I was just wondering if there was a minimum python version? I couldn't find any explicit mention so I've currently set it to `3.0`. Many thanks!

**Comment by bpozdena** [comment]
3.6+ should be fine for now.

**Comment by chewblacka** [comment]
> 3.6+ should be fine for now.

Much appreciated!
