### ISSUE TITLE
"Unsupported OneDrive client, please upgrade it!", but it's already the latest available version

### ISSUE THREAD

**Issue by Slater91** [bpozdena/OneDriveGUI#131]
Hello. I have just tried to run OneDrive GUI, but unfortunately it detects my onedrive 2.4.25 install as old and not supported. This is currently the latest available version.

My setup is as follows:
- OS: KDE neon (based on Ubuntu 22.04)
- onedrive 2.4.25 installed through OpenSUSE build service as detailed [here](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#distribution-ubuntu-2204)

Here is the output when starting from the terminal:

> 2023-11-04 12:13:20,155 [OneDriveGUI.py:3030][fn=main_window_start_state][INFO] - [GUI] Starting OneDriveGUI minimized to system tray
> 2023-11-04 12:13:20,157 [OneDriveGUI.py:1101][fn=__init__][INFO] - my@email.com
> 2023-11-04 12:13:20,660 [connectionpool.py:1053][fn=_new_conn][DEBUG] - Starting new HTTPS connection (1): api.github.com:443
> 2023-11-04 12:13:21,050 [connectionpool.py:547][fn=_make_request][DEBUG] - https://api.github.com:443 "GET /repos/abraunegg/onedrive/releases/latest HTTP/1.1" 200 1244
> 2023-11-04 12:13:21,106 [OneDriveGUI.py:2480][fn=client_version_check][DEBUG] - [GUI] Client version check: {'latest_client_version': 'v2.4.25', 'installed_client_version': 'v2.4.25'}
> 2023-11-04 12:13:21,109 [OneDriveGUI.py:2553][fn=autostart_monitor][DEBUG] - [my@email.com] Compatible client version found: False
> 2023-11-04 12:13:21,110 [OneDriveGUI.py:2554][fn=autostart_monitor][DEBUG] - [my@email.com] Auto-sync enabled for profile: True

Any idea of why this happens? It doesn't seem to make much sense to me. Thanks.

EDIT: I realised that I had mistakenly downloaded the 1.1.0 Alpha instead of version 1.0.3. Sorry for the confusion. Still, this seems to be a relevant issue, considering it says "fix client version verification" in the changelog!

**Comment by bpozdena** [comment]
What version of the GUI are you using and how did you install it?

**Comment by Slater91** [comment]
I mentioned it in the edit: version 1.1.0 Alpha. I ran it through the AppImage. It should be noted that version 1.0.3 works perfectly.

**Comment by bpozdena** [comment]
1.1.0alpha is only compatible with onedrive 2.5.0alpha versions. There will
not be backwards compatibility as there are too many changes.

**Comment by Slater91** [comment]
Then please mention this in the changelog, otherwise it's going to be unnecessarily confusing to users!

**Comment by bpozdena** [comment]
Done. I will also try to improve the messages in the GUI.

**Comment by Slater91** [comment]
Thank you so much for your work! Keep it up!

**Comment by bpozdena** [comment]
This will 'fix itself' once the client v2.5 is official released on GitHub.
