### ISSUE TITLE
Publish to native distribution-specific package manager repositories.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bpozdena/OneDriveGUI#133]
I can download https://software.opensuse.org/download/package?package=onedrive&project=openSUSE%3AFactory but yours isn't available (yet?)

**Comment by bpozdena** [comment]
I only package OneDriveGUI as AppImage, which can be downloaded in the[ release section](https://github.com/bpozdena/OneDriveGUI/releases). 

Sorry, I will not provide any distro specific packages as I would not have the time to maintain them.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpozdena/OneDriveGUI/issues/133#issuecomment-1817094073

That's reasonable. I expected that. Thanks regardless. I can always try to maintain one myself, @bpozdena.
