### ISSUE TITLE
Specify that the value in the top right corresponds to free space, not amount to be downloaded.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bpozdena/OneDriveGUI#139]
As https://github.com/bpozdena/OneDriveGUI/discussions/135#discussion-5859082 demonstrates:

<blockQuote>

https://onedrive.live.com/?v=managestorage reports that I have used

> 909.3 GiB of 1.5 TiB

Yet https://github.com/bpozdena/OneDriveGUI reports

> ![169.7 GiB](https://github.com/bpozdena/OneDriveGUI/assets/42837531/b859092b-ed20-4bec-be70-3c2e83d0f61c)

Does this mean that it shall solely synchronize some of my drive? Which parts?

</blockQuote>

...without clarification, this is not obvious.

**Comment by bpozdena** [comment]
The free space is reported by the OneDrive Client. Please run the AppImage from your terminal, start sync and copy/screenshot the reported free space.

Example:
![image](https://github.com/bpozdena/OneDriveGUI/assets/24818591/c8e6f88c-4ede-4b95-b344-fec67047c750)

**Comment by RokeJulianLockhart** [comment]
I wasn't aware that it was reporting free space - in that regard, it's almost definitely correct. I believed that it displayed how much was to be downloaded. This should be specified, although would warrant a new issue or a renaming of this one.

**Comment by RokeJulianLockhart** [comment]
This should be specified, although would warrant a new issue or a renaming of this one.

**Comment by bpozdena** [comment]
When you hover your mouse cursor over the value, it should explain what it means.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpozdena/OneDriveGUI/issues/139#issuecomment-1817404065

@bpozdena, that's unintuitive too. A button with the label "help" and a question mark icon would probably be superior to a hover.
