### ISSUE TITLE
Allow enforcing one-way synchronization.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bpozdena/OneDriveGUI#140]
**https://github.com/bpozdena/OneDriveGUI/discussions/136#discussion-5859087**

> I don't trust OneDriveGUI entirely yet, so I'd like to know how to ensure that it's solely performing a one-way sync — after all, if the synchronization process breaks somehow, it might sync the breakage back to the server.

**Comment by RokeJulianLockhart** [comment]
This is possible via the command line, per https://github.com/bpozdena/OneDriveGUI/discussions/136#discussioncomment-7602761

<blockQuote>

`onedrive --help`

> ```.log
>   --download-only
>       Replicate the OneDrive online state locally, by only downloading changes from OneDrive. Do not upload local changes to OneDrive.
> ```

</blockQuote>

but I'd like to be able to perform it on the GUI.

**Comment by bpozdena** [comment]
Download/Upload only options can be enabled in the GUI:
![image](https://github.com/bpozdena/OneDriveGUI/assets/24818591/e7be3143-1c95-4f23-b006-d7ca795bfef4)

You can hover your mouse over the options to get a very brief description of the feature. Check the [OneDrive Client documentation](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a-one-way-download-sync) for more details.

**Comment by RokeJulianLockhart** [comment]
Apologies. I missed that!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpozdena/OneDriveGUI/issues/140#issuecomment-1817075480

@bpozdena, I don't see that GUI. Is that because I'm not using the alpha?

> ![20231118T030658GMT](https://github.com/bpozdena/OneDriveGUI/assets/42837531/8fb777e1-9b60-46fb-b07e-1be82a33443a)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpozdena/OneDriveGUI/issues/140#issuecomment-1818067592

I wasn't aware that two configuration pages existed.
