### ISSUE TITLE
Undoing configuration change which required resync should remove necessity to resync.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bpozdena/OneDriveGUI#141]
I instructed https://github.com/bpozdena/OneDriveGUI/ to check for `.nomount` and `.nosync` files, which caused

> ![20231120T012724GMT](https://github.com/bpozdena/OneDriveGUI/assets/42837531/5bcceafc-d61c-4453-801a-12bb4b00158d)

but undoing this doesn't prevent it forcing me to resync. I have almost 1 TiB of content to synchronize, and have downloaded an awful lot already, so this simply isn't feasible.

**Comment by abraunegg** [comment]
@RokeJulianLockhart 
This GUI application uses https://github.com/abraunegg/onedrive under the hood. 

The documentation for `--resync` details this as to what triggers a resync requirement:
* v2.4.x : https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#performing-a---resync
* v2.5.x : https://github.com/abraunegg/onedrive/blob/onedrive-v2.5.0-alpha-3/docs/usage.md#performing-a-resync

In either application version, changing:
```
Config option 'check_nosync'                 = true
Config option 'check_nomount'                = true
```

Should not - and does not trigger a `--resync` requirement:
```
Config option 'check_nosync'                 = false
Config option 'check_nomount'                = false
```
results in (v2.4.x):
```
Using 'user' Config Dir: /home/alex/.config/onedrive
Using 'system' Config Dir: /etc/onedrive
Configuration file successfully loaded
config file has been updated, checking if --resync needed        <--- config file was updated, but no resync was triggered
Using logfile dir: /var/log/onedrive/
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Using Curl defaults for all HTTP operations
Opening the item database ...
All operations will be performed in: /home/alex/OneDrive
Application version: v2.4.25-11-g4a60654
..........
```

and in v2.5.x:
```
Reading configuration file: /home/alex/.config/onedrive/config
Configuration file successfully loaded
Using 'user' configuration path for application state data: /home/alex/.config/onedrive
Using the following path to store the runtime application log: /var/log/onedrive
Application configuration file has been updated, checking if --resync needed      <--- config file was updated, but no resync was triggered
Checking Application Version ...
Attempting to initialise the OneDrive API ...
Configuring Global Azure AD Endpoints
The OneDrive API was initialised successfully
Opening the item database ...
Application version:  v2.5.0-alpha-3 GitHub version: v2.4.25-26-g9837e59
....................
```

If a resync is required, the application will also exit with a `126` error code.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpozdena/OneDriveGUI/issues/141#issuecomment-1821563610

Thanks, @abraunegg - so this would need to be requested at https://github.com/abraunegg/onedrive/issues/new/choose because it's not something this GUI decides, and regardless, it's been fixed in `2\.5.*`?

**Comment by abraunegg** [comment]
> > [#141 (comment)](https://github.com/bpozdena/OneDriveGUI/issues/141#issuecomment-1821563610)
> 
> Thanks, @abraunegg - so this would need to be requested at https://github.com/abraunegg/onedrive/issues/new/choose because it's not something this GUI decides, and regardless, it's been fixed in `2\.5.*`?

v2.4 and v2.5 DO NOT ask for a resync when those options are enabled|disabled
