### ISSUE TITLE
onedrive freezing when started through GUI

### ISSUE THREAD

**Issue by robertschulze** [bpozdena/OneDriveGUI#145]
Working on Ubuntu 22.04 LTS with onedrive onedrive v2.4.25-1+np1 and OneDriveGUI-1.0.3_fix116-x86_64.AppImage

When I start the synchronization using the GUI, it freezes after ~5 files indefinitely while if I start onedrive from the command line using `onedrive --confdir=/home/robert/.config/onedrive/accounts/xyz@mydomain.net --monitor -v` it is working fine. 

Is there any log that would help get to the bottom of it? Or maybe it is a known issue?
Thanks,
Robert

**Comment by bpozdena** [comment]
Can you please start the AppImage from terminal, reproduce the issue and then share all the output from the terminal?
Feel free to mask any personal details.

**Comment by robertschulze** [comment]
[GUI.onedrive-gui.log](https://github.com/bpozdena/OneDriveGUI/files/13690188/GUI.onedrive-gui.log)
[GUI.robert.onedrive.log](https://github.com/bpozdena/OneDriveGUI/files/13690189/GUI.robert.onedrive.log)
[CONSOLE.robert.onedrive.log](https://github.com/bpozdena/OneDriveGUI/files/13690209/CONSOLE.robert.onedrive.log)
Hi, this is the output to the console and log file(s) when running in GUI or on CONSOLE. You can see that it just stops. I don't know why/how...

**Comment by bpozdena** [comment]
Thanks for the logs. I'm not sure what could be the cause...

It seems the GUI asked you to perform a resync. Can you test the resync option from the console client?

1) start the sync from terminal as usual:
`onedrive --confdir='/home/user/.config/onedrive/accounts/name@domain.com' --monitor -v`

2) wait until the sync cycle completes, just to make sure all files are in sync. Then stop the client.
3) start the client again with enforced resync and let me know if there are any issues.
`onedrive --confdir='/home/user/.config/onedrive/accounts/name@domain.com' --monitor -v --resync --resync-auth`

If you still don't see any issues, I'll probably have to make an appimage with higher debug verbosity. But it might take a few days before I get to a PC.

In the meantime, you can also try to run the GUI directly from source and see if you can reproduce it there as well?
