### ISSUE TITLE
[alpha] Sync can't start on some systems when legacy shared folders are used

### ISSUE THREAD

**Issue by bpozdena** [bpozdena/OneDriveGUI#146]
I might get a bit of a time to work on this project again...

Sync can't start on some systems when legacy shared folders are used during migration from client v2.4
RN: warn if sync_business_shared_folders is used
Error: Unknown key in config file: sync_business_shared_folders

config:
sync_business_shared_folders = "true"

**Comment by abraunegg** [comment]
@bpozdena 
Specific to this - please read: https://github.com/abraunegg/onedrive/blob/onedrive-v2.5.0-alpha-4/docs/business-shared-folders.md

It is not just the 'config' flag that needs taking care of, there are a number of actions needed.

**Comment by abraunegg** [comment]
@bpozdena 
FYI the entire OneDrive Business Shared Items feature has now been 100% re-written.

Please refer to https://github.com/abraunegg/onedrive/blob/Implement-Feature-Request-1300/docs/business-shared-items.md for details.

My aim is to add this to 'alpha-5' , then push a 'beta' or 'release-candidate' out
