### ISSUE TITLE
OneDriveGUI-1.0.3 : Not working with Ubuntu 23.10 / Python 3.11

### ISSUE THREAD

**Issue by swinder0161** [bpozdena/OneDriveGUI#154]
Logs atatched: [debug.log](https://github.com/bpozdena/OneDriveGUI/files/14061034/debug.log)

I have tried the release version and also the main branch tip of today

**Comment by bpozdena** [comment]
The log does not show anything, just that you have not configured any onedrive profiles.
Please provide a detailed description of the issue with screenshots. Also specify how you are starting the GUI and how you installed it.

**Comment by swinder0161** [comment]
Hi @bpozdena 

My profile is set, seems first log didnot capture it.
I am running from source checked out to v1.0.3 tag and running command: `python3 OneDriveGUI.py`

Uploading new logs: 
[OneDriveGUI-crash.log](https://github.com/bpozdena/OneDriveGUI/files/14068342/OneDriveGUI-crash.log)

Please guide, how to enable the app.

**Comment by swinder0161** [comment]
`apt install libxcb-cursor0`

fixed the problem
