### ISSUE TITLE
OneDriveGUI crashes at start when using Gear Lever

### ISSUE THREAD

**Issue by jsnoriegam** [bpozdena/OneDriveGUI#155]
Good day,

I've recently started to use Gearlever to manage my appimages, and all my apps work except onedrivegui, that fails at start with this trace:

```
Traceback (most recent call last):
  File "/tmp/.mount_gearleqfMvWa/usr/src/OneDriveGUI.py", line 65, in <module>
    from ui.ui_login import Ui_LoginWindow
  File "/tmp/.mount_gearleqfMvWa/usr/src/ui/ui_login.py", line 18, in <module>
    from PySide6.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PySide6.QtWebEngineWidgets'
```

Pretty much like this issue: https://github.com/bpozdena/OneDriveGUI/issues/59

But it worked fine before I used gearlever.

So I did a little reading on the aforementioned issue and i found that you do this check to verify if the app is running as an appimage:

`APPIMAGE = True if "tmp/.mount_one" in DIR_PATH.lower() else False`

But gearlever prefixes every appimage with "gearlever_" so the mount path is always something like "/tmp/.mount_gearleXXXXX" and so that check always return false.

Is there another way to check if the app is running as appimage?

For the time being I'll be using onedrivegui outside gearlever but I'll like to have all my appimages in one place.

I'm using OneDriveGUI-1.0.3_fix150-x86_64.AppImage.

Thanks.

**Comment by tl-pierre** [comment]
Same problem for me with GearLever

**Comment by bpozdena** [comment]
The AppImage detection is already removed in the RC1 branch. QtWebEngine login will be configurable in the GUI Settings window. 
![image](https://github.com/bpozdena/OneDriveGUI/assets/24818591/56779fd4-c98e-4c6d-adcb-f48983f9782d)
