### ISSUE TITLE
unsupported onedrive client please update

### ISSUE THREAD

**Issue by svefro** [bpozdena/OneDriveGUI#158]
![Screenshot_20240229_191252](https://github.com/bpozdena/OneDriveGUI/assets/5417494/3a140077-6ed1-4c1f-886b-f81237466b5e)

what to do? im on the latest version

output from apt install:
````
Unpacking onedrive (2.4.25-1+np1) ...
Setting up libphobos2-ldc-shared100:amd64 (1:1.30.0-1) ...
Setting up onedrive (2.4.25-1+np1) ...
Processing triggers for man-db (2.11.2-3) ...
Processing triggers for libc-bin (2.38-1ubuntu6.1) ...

````

**Comment by bpozdena** [comment]
What does it mean exactly "latest version"?

**Comment by svefro** [comment]
last released version here https://github.com/abraunegg/onedrive/releases

Is that not supported?

your readme.md says "Minimum supported OneDrive client v2.4.15"

**Comment by svefro** [comment]
Nevermind. i was using the alpha version of the gui. no support for 2.4.xx
