### ISSUE TITLE
Unsupported OneDrive client! reported for v2.4.25

### ISSUE THREAD

**Issue by andyhardy** [bpozdena/OneDriveGUI#162]
**Describe the bug**
Installed latest version of onedrive and installed latest version of OneDriveGUI appimage.

Running OneDriveGUI reports that the version of onedrive is not compatible and needs upgrading.

**Log**
2024-04-06 19:14:12,538 [connectionpool.py:549][fn=_make_request][DEBUG] - https://api.github.com:443 "GET /repos/abraunegg/onedrive/releases/latest HTTP/1.1" 200 1244
2024-04-06 19:14:12,560 [OneDriveGUI.py:2424][fn=client_version_check][DEBUG] - [GUI] Client version check: {'latest_client_version': 'v2.4.25', 'installed_client_version': 'v2.4.25'}
2024-04-06 19:14:12,564 [OneDriveGUI.py:2498][fn=autostart_monitor][DEBUG] - [xxx@xxx] Compatible client version found: False

**System Info**
 - Linux distribution: Ubuntu 23.10
 - Desktop environment:  Gnome
 - Compositor: [e.g. Wayland]
 - Python version: 3.11.6
 - Version of OneDrive client: v2.4.25

**OneDriveGUI info**
How did you install OneDriveGUI?: (https://github.com/bpozdena/OneDriveGUI/releases
What is the name of the AppImage file (if applicable)? : OneDriveGUI-1.1.0rc1-x86_64.AppImage

**Comment by bpozdena** [comment]
Glad to see all works as expected...

**Comment by andyhardy** [comment]
So... v2.4.25 is the latest version of onedrive but it's **not** supported by OneDriveGUI and the error message is to install the latest version of onedrive?

**Comment by claudio-walser** [comment]
I want to support @andyhardy, 2.4.25 is the current stable release and you don't support it.
What is the intention of this? Pre-Releases aren't in official package repos as well, everybody would have to compile it from source.

**Comment by claudio-walser** [comment]
Additionally, you seem to support 2.4.15 as a minimum version, this seem not to work properly:
https://github.com/bpozdena/OneDriveGUI/blob/main/src/OneDriveGUI.py#L164

**Comment by bpozdena** [comment]
You are complaining about a pre-release version OneDriveGUI-1.1.0rc1. Please read the description of what you are downloading : https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.1.0rc1 

Use the standard release v1.0.3 AppImage with OneDrive client v2.4.X.

**Comment by claudio-walser** [comment]
Thank you, this works. I was not scrolling down enough in your releases, since i've seen alpha releases after the rc1 :see_no_evil: 
Thank you for clarification.
