### ISSUE TITLE
Cannot add a Sharepoint Shared Library with spaces in its name

### ISSUE THREAD

**Issue by AcidWindsurf** [bpozdena/OneDriveGUI#163]
**Describe the bug**
When trying to add a Shared Library with spaces in its name, for example "Some Shared Library", clicking in "Create Profile" does nothing, only option working is "Cancel". No warning or errors showing.

**To Reproduce**
- click "Profile" icon in GUI app.
- click "Add Profile" button
- choose "Add SharePoint Shared Library", then "Next" button
- click "Get SharePoint Sites"
- select a SharePoint Site (all shared sites show correctly, regardless of spaces or special chars in names)
- click "Get Shared Libraries"
- select a SharePoint Shared Library (all shared libraries show correctly, regardless of spaces or special chars in names)
- click "Create Profile" --> nothing happens, "Next" button remains grayed out, cannot go ahead.

**Expected behavior**
After following those steps, "Next" button becomes available and clicking on it creates a profile, which can be later customized.

**Screenshots**
![imagen](https://github.com/bpozdena/OneDriveGUI/assets/70342004/471a476b-333d-4b53-b6c3-5a8fad6377a2)

**Log**
If applicable, add relevant output from log file `/tmp/onedrive-gui/onedrive-gui.log`.

2024-04-09 14:14:56,956 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [UTN] Sync with OneDrive is complete
2024-04-09 14:15:36,149 [OneDriveGUI.py:1143][fn=stop_unsaved_changes_timer][DEBUG] - [GUI] Stopping timer for unsaved changes checker
2024-04-09 14:15:36,149 [OneDriveGUI.py:448][fn=create_library_profile][INFO] - [GUI] Available Libraries:  {'Class Materials': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'Documentos': 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'}

(real IDs hidden for privacy)

**System Info**
 - Linux distribution: Ubuntu 22.04.04 LTS
 - Desktop environment:  Gnome 42.9
 - Compositor: Wayland
 - Python version: 3.10.6-1~22.04
 - Version of OneDrive client: 2.4.25-1+np2+4.1

**OneDriveGUI info**
How did you install OneDriveGUI?: AppImage
What is the name of the AppImage file (if applicable)? : OneDriveGUI-1.0.3-x86_64.AppImage

**Additional context**

**Comment by bpozdena** [comment]
Hi @AcidWindsurf ,

thanks for the report. This issue is already fixed in the v1.1 releases. 

Could you please test [OneDriveGUI v1.1.0rc1](https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.1.0rc1) ?

Just note that this version is only compatible with the latest [OneDrive Client Version v2.5.0-rc1](https://github.com/abraunegg/onedrive/discussions/2662), which you will need to manually compile. 

NOTE: OneDrive Client Version v2.5.0-rc1 does not allow listing of shared libraries while sync is running. You will need to temporarily stop the sync while adding the Shared Library.

**Comment by abraunegg** [comment]
@bpozdena 
> NOTE: OneDrive Client Version v2.5.0-rc1 does not allow listing of shared libraries while sync is running. You will need to temporarily stop the sync while adding the Shared Library.

FYI - that issue was fixed via https://github.com/abraunegg/onedrive/pull/2661/commits/68d6921a11244113600552d03e72a01ac2dbbc71 3 weeks ago ..
