### ISSUE TITLE
Can I install OneDrive in Ubuntu 18.04 ? I did all the steps but when I try to run it, I got an error GLIBC_2.28 not found

### ISSUE THREAD

**Issue by migj20032024** [bpozdena/OneDriveGUI#165]
**Describe the bug**
When I run the cmd "python3 OneDriveGUI.py" , it does run and I get the following error messages:
Traceback (most recent call last):
  File "OneDriveGUI.py", line 14, in <module>
    from PySide6.QtCore import QThread, QTimer, QUrl, Signal, QFileInfo, Qt
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/marcos/.local/lib/python3.7/site-packages/PySide6/Qt/lib/libQt6Core.so.6)

**To Reproduce**
Whenever I try to run it

**Expected behavior**
NA

**Screenshots**
![image](https://github.com/bpozdena/OneDriveGUI/assets/166714446/a2bf1692-4784-4c7a-88b8-38d18822d63b)

**Log**
NA

**System Info**
 - Linux distribution: [e.g. Ubuntu 22.04]
 - Desktop environment:  [e.g. Gnome]
 - Compositor: [e.g. Wayland]
 - Python version: [e.g. 3.11]
 - Version of OneDrive client [e.g. v2.4.25]

![image](https://github.com/bpozdena/OneDriveGUI/assets/166714446/9614079e-6c8a-498b-b8e3-a5e6db78442f)

or output of below commands:
```sh
lsb_release -a
echo $XDG_CURRENT_DESKTOP
loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
python --version
onedrive --version
```

**OneDriveGUI info**
How did you install OneDriveGUI?: [AppImage/source/AUR] - Download from Github
What is the name of the AppImage file (if applicable)? : [e.g OneDriveGUI-1.x.x-x86_64.AppImage]

**Additional context**

**Comment by bpozdena** [comment]
Looks like you did not install all dependencies. If you don't know how to do it, please use the AppImage, which has all the dependencies packages in.
