### ISSUE TITLE
QT import error

### ISSUE THREAD

**Issue by zany130** [bpozdena/OneDriveGUI#166]
**Describe the bug**
ondrivegui does not launch erroring out with 

```sh
onedrivegui
Traceback (most recent call last):
  File "/usr/bin/onedrivegui", line 15, in <module>
    from PySide6.QtGui import QIcon, QPixmap, QDesktopServices
ImportError: /usr/lib/python3.11/site-packages/PySide6/QtGui.abi3.so: undefined symbol: _ZN5QFont11tagToStringEj, version Qt_6
```
**To Reproduce**
1. run `onedrivegui`
2. see error

**Expected behavior**
onedrivegui launches with no error

**Log**
no logs under `/tmp/`
**System Info**
 - Linux distribution: Garuda Linux
 - Desktop environment:  KDE
 - Compositor: Wayland
 - Python version: 3.11.8
 - Version of OneDrive client v2.4.25

or output of below commands:
```sh
LSB Version:	n/a
Distributor ID:	Garuda
Description:	Garuda Linux
Release:	Soaring
Codename:	Spizaetus
KDE
wayland
Python 3.11.8
onedrive v2.4.25
```

**OneDriveGUI info**
How did you install OneDriveGUI?: AUR

```
pacman -Qi onedrivegui-git
Name            : onedrivegui-git
Version         : 1.1.0alpha5.r2.g9f9df60-1
Description     : A simple GUI for OneDrive Linux client, with multi-account support.
Architecture    : any
URL             : https://github.com/bpozdena/OneDriveGUI
Licenses        : GPL-3.0-or-later
Groups          : None
Provides        : onedrivegui
Depends On      : pyside6  python-requests  onedrive-abraunegg  qt6-webengine
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : onedrivegui
Replaces        : None
Installed Size  : 552.83 KiB
Packager        : Unknown Packager
Build Date      : Fri 12 Apr 2024 01:53:16 PM EDT
Install Date    : Fri 12 Apr 2024 01:53:22 PM EDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by AlwynYin** [comment]
Same issue here, running ArchLinux

**Comment by bpozdena** [comment]
Sorry, I can't support any packages other then AppImage. It looks like it's missing dependencies and installs wrong version of the Onedrive Client. Please contact the AUR package maintainer for help. I think the non git AUR package worked fine last time o used it - try that instead.


Or just use the AppImage, which I provide and support.

**Comment by AlwynYin** [comment]
an update solved the problem, apologies for interrupting you and the developers for an unrelated issue, sorry.

**Comment by Serega007RU** [comment]
> an update solved the problem

What have you updated? how did you manage to solve the problem?
