### ISSUE TITLE
Potential version mismatch with client.

### ISSUE THREAD

**Issue by RenanSP13** [bpozdena/OneDriveGUI#176]
Hi! Following abraunegg's installation steps for Pop OS 22.04 (which is listed as supported), I get the version v2.4.25 of the onedrive client. 

![Screenshot from 2024-06-13 08-37-09](https://github.com/bpozdena/OneDriveGUI/assets/94800810/8062e28d-eb5a-4a29-8b0b-24fa85c15dad)
![Screenshot from 2024-06-13 08-30-40](https://github.com/bpozdena/OneDriveGUI/assets/94800810/1bae3ac8-3dee-4b30-a6af-f067674de59d)

Unfortunately, the GUI tells me I need to upgrade the client.

![Screenshot from 2024-06-13 08-31-35](https://github.com/bpozdena/OneDriveGUI/assets/94800810/d5228f67-a792-4947-94a1-f4314bc2397c)

Could you, please, point out the mistake? Thanks!

**Comment by leojimenezcr** [comment]
Hi. Same issue in Ubuntu 22.04.

The version check compare numbers, ignoring the "v" and the points (.). But this version contain another chars like "+", "n" or "p". Maybe it is the issue.

Current version:
`$ onedrive --version
onedrive v2.4.25-1+np2+4.1`

**Comment by abraunegg** [comment]
@leojimenezcr , @RenanSP13 
You are *both* missing adding some *critical* information here ... what OneDrive GUI version are you running?

**Comment by leojimenezcr** [comment]
Hi. I am using OneDriveGUI-1.1.0rc1-x86_64.AppImage

**Comment by RenanSP13** [comment]
You are absolutely right, [leojimenezcr](https://github.com/leojimenezcr)
I was trying to use a "pre-release" version of OneDriveGUI, when I should instead have used the "latest" one (v1.0.3). That solved my issue. Thanks!

**Comment by abraunegg** [comment]
Exactly ... please read the version release notes more *carefully* .....

**Comment by leojimenezcr** [comment]
Thanks for the support ;-)
