### ISSUE TITLE
Version check fails but requirements met

### ISSUE THREAD

**Issue by rijnhard** [bpozdena/OneDriveGUI#177]
**Describe the bug**
A compatible version is installed, but the version check fails.

**To Reproduce**
Launch on Fedora 40 from AppImage

**Expected behavior**
Version check should pass.

**Screenshots**
![Screenshot_20240717_122411](https://github.com/user-attachments/assets/4112fb32-4d44-4378-8bbc-73dd24ddca6b)

**Log**
```
rijnhard@fedora:~$ ./OneDriveGUI-1.1.0rc1-x86_64_f16390b793edcbe0573a9ff34acad941.AppImage
[OneDriveGUI.py:3122][fn=config_client_bin_path][INFO] - Onedrive client location: 'onedrive'
[OneDriveGUI.py:2883][fn=get_installed_client_version][DEBUG] - [GUI] Installed client version is 2425
[connectionpool.py:1055][fn=_new_conn][DEBUG] - Starting new HTTPS connection (1): api.github.com:443
[connectionpool.py:549][fn=_make_request][DEBUG] - https://api.github.com:443 "GET /repos/abraunegg/onedrive/releases/latest HTTP/1.1" 200 1198
[OneDriveGUI.py:2424][fn=client_version_check][DEBUG] - [GUI] Client version check: {'latest_client_version': 'v2.4.25', 'installed_client_version': 'v2.4.25'}
[OneDriveGUI.py:2498][fn=autostart_monitor][DEBUG] - [rijnhard@<snip>] Compatible client version found: False
[OneDriveGUI.py:2501][fn=autostart_monitor][DEBUG] - [rijnhard@<snip>] Auto-sync enabled for profile: False
```

**System Info**
 - Linux distribution: Fedora F40
 - Desktop environment:  KDE 6.1
 - Compositor: Wayland
 - Python version: Python 3.12.4
 - Version of OneDrive client: v2.4.25

**OneDriveGUI info**
How did you install OneDriveGUI?: AppImage
What is the name of the AppImage file (if applicable)? : `OneDriveGUI-1.1.0rc1-x86_64_f16390b793edcbe0573a9ff34acad941.AppImage`

**Comment by abraunegg** [comment]
@rijnhard 
Please *re-read* everything .... you have installed a *beta* GUI ..

**References:**
* https://github.com/bpozdena/OneDriveGUI/releases
* https://github.com/bpozdena/OneDriveGUI/issues/176
* https://github.com/bpozdena/OneDriveGUI/issues/174
* many more ..........
