### ISSUE TITLE
AppImage 1.0.3_fix150 does not launch in Ubuntu 24.04

### ISSUE THREAD

**Issue by fvroig** [bpozdena/OneDriveGUI#179]
The AppImage version 1.0.3_fix150 fails to start when launched in a fresh installation of Ubuntu Budgie 24.04. Here's the full output:

`2024-08-01 22:19:01,221 [OneDriveGUI.py:3093][fn=config_client_bin_path][INFO] - Onedrive client location: 'onedrive'`
`2024-08-01 22:19:01,298 [OneDriveGUI.py:2854][fn=get_installed_client_version][DEBUG] - [GUI] Installed client version is 2425`
`2024-08-01 22:19:01,306 [OneDriveGUI.py:2889][fn=create_global_config][DEBUG] - [GUI] - loading default config {'onedrive': {'sync_dir': '"~/OneDrive"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"false"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '""'}}`
`2024-08-01 22:19:01,307 [OneDriveGUI.py:2933][fn=create_global_config][DEBUG] - [GUI]{}`
`qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.`
`This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`
`Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.`

Any clues?

**Comment by bpozdena** [comment]
Your bug report is not complete. Please open a new bug with all requested details if you need my help. Before opening a new issue also search in previously closed issues. You'll likely find answers there.
