### ISSUE TITLE
Missing Tray Icon in Gnome 41

### ISSUE THREAD

**Issue by mercifulboss** [bpozdena/OneDriveGUI#18]
Hello, this is the onedrive app I've been waiting for a long time. So far I see no issues with it. Thank you for making it.

Would it be possible to make it have an icon in the tray so that clicking the icon would open the GUI? Currently I'm using GNOME and it shows as a "settings" icon so I cannot favorite it and save it onto my dock and doesn't have a tray icon, meaning i'd need to launch it with a terminal command. It would be convenient if these desktop elements were implemented.

![Screenshot from 2022-02-10 17-43-26-2](https://user-images.githubusercontent.com/90151527/153511227-dfb966de-a82f-422c-9995-d1f2bf364ae4.png)

Apologies if you were already planning to implement this. This is my one request for this already amazing program.

**Comment by bpozdena** [comment]
Thanks for your feedback @mercifulboss 

- Regarding the tray icon, it is already implemented and works on KDE, XFCE, Cinnamon, Gnome 40 and even on Windows 10. Unfortunately, I don't know how to make the tray icon work on latest Fedora 35 with Gnome 41. It looks like the Gnome devs just want to go against the flow at all cost. Maybe you can try your luck with this Gnome extension https://github.com/MartinPL/Tray-Icons-Reloaded . It did not work for me though. I've already spent many hours on this and have given up. 

Example from Ubuntu 21.10 (Gnome 40.4)
![image](https://user-images.githubusercontent.com/24818591/153630261-a8bf8cc4-1f16-42c7-883a-53a3634f23f3.png)



- Regarding the reported application name and icon in Gnome activities, I don't have a solution either. But I have not given up yet :-). I have so far only been able to create the activity icon with the bellow steps. You can use it to launch the GUI, but it will still show as a separate python3 application. I will need to invest more time into this. Feel free help with the research on how this actually works on Gnome.

1) Download the latest ```OneDriveGUI.py``` from main branch.

1) Make ```OneDriveGUI.py``` executable

1) Create file ```~/.local/share/applications/OneDriveGUI.desktop``` with the bellow content. Ensure to update the data path.

      ```
      [Desktop Entry]
      Name=OneDriveGUI
      StartupNotify=true
      Exec=/<correct_path>/OneDriveGUI/src/OneDriveGUI.py
      Terminal=false
      Path=/<correct_path>/OneDriveGUI/src/
      Icon=/<correct_path>/OneDriveGUI/src/resources/images/icons8-clouds-48.png
      Type=Application
      ```

1) run command ```sudo update-desktop-database```
1) result
![image](https://user-images.githubusercontent.com/24818591/153630511-90e855fa-336b-4d7a-a78f-fc1f5deaab70.png)

**Comment by bpozdena** [comment]
I did a few more tests on Gnome 41.3 based Fedora and Manjaro and all worked as expected in both cases. The catch is that you must run Gnome under X11. It does not work under Wayland and unfortunately, I do not know if there is anything I can do to fix it. So I will just close this bug for now.

Manjaro currently still uses X11 by default and Fedora uses Wayland. Switching to X11 is very easy: https://docs.fedoraproject.org/en-US/quick-docs/configuring-xorg-as-default-gnome-session/
