### ISSUE TITLE
[BUG] Button outside screen area with 150% system scaling

### ISSUE THREAD

**Issue by 7HE-W0R1D** [bpozdena/OneDriveGUI#188]
**Describe the bug**
I have my system scale set to 150% due to the size of my screen. When editing the profile, the "add profile" and "save changes" buttons are below the screen when its full screen, making it impossible to click with a mouse. 

A walkaround for that would be to use tab & enter to click. Also, when windowed, the minimum size that the window allows is also too big, blocking the buttons at the bottom

**To Reproduce**
1. Set system scaling to > 100% (I have a 1920 x 1080, 13.3in screen with 150% scale)
2. Open OneDrive GUI and open profile settings
3. Move the profile settings window full screen
4. Try to add a new profile or save changes to the current one, buttons will be blocked
5. Resize the profile settings window to the smallest possible
6. Try again to add a new profile or save changes to the current one, buttons will still be blocked
7. 
...

**Expected behavior**
...description of expected behavior...

**Screenshots**
![Screenshot From 2024-09-21 21-28-31](https://github.com/user-attachments/assets/9bb59295-d93b-4087-9579-7cc200bcff6c)
Window when resized to the smallest

![image](https://github.com/user-attachments/assets/0b9b54f2-058c-43d6-b7ac-d5ad8e40a08e)
Window when fullscreened

**Log**

**System Info**
 - Linux distribution: Fedora 41 Silverblue
 - Desktop environment:  GNOME 47
 - Compositor: Wayland
 - Python version: Python 3.13.0rc2
 - Version of OneDrive client: 2.5.0

**OneDriveGUI info**
How did you install OneDriveGUI?: AppImage
What is the name of the AppImage file (if applicable)? : OneDriveGUI-1.1.0-x86_64.AppImage

**Comment by bpozdena** [comment]
I've changed the layout slightly and added a scroll bar on the sync option page, which will show when the window is too small. 
![image](https://github.com/user-attachments/assets/f56b7808-1532-41e4-8089-628cc64a15d0)
