### ISSUE TITLE
[BUG] 'OneDrive is processing items' while the button is not started

### ISSUE THREAD

**Issue by arisliang** [bpozdena/OneDriveGUI#191]
**Describe the bug**
'OneDrive is processing items' while the button is not started

**To Reproduce**
1. Open OneDriveGUI by double click the AppImage file
2. Click start

**Expected behavior**
Complete sync and button not started

**Screenshots**
![image](https://github.com/user-attachments/assets/19f22a8a-78e0-470a-bbab-245f067c4883)

**Log**
If applicable, add relevant output from log file `/tmp/onedrive-gui/onedrive-gui.log`.

> core.exception.AssertError@src/itemdb.d(725): The DB record mtime entry is not a valid ISO timestamp entry. Please attempt a --resync to fix the local database

**System Info**
 - Linux distribution: Ubuntu 22.04
 - Desktop environment:  [e.g. KDE Plasma 6.1.4]
 - Compositor: [Wayland/X11]
 - Python version: 3.12.1
 - Version of OneDrive client: 2.5.1

**OneDriveGUI info**
How did you install OneDriveGUI?: AppImage
What is the name of the AppImage file (if applicable)? : OneDriveGUI-1.1.1-x86_64.AppImage

**Comment by bpozdena** [comment]
I'll improve the client crash detection. I'll also show a GUI pop up message notifying users that the client crashed. I'll also add a resync button.

But I can't fix the client crash itself. Please try running the sync from CLI and report the crash on the onedrive client GitHub page.

**Comment by abraunegg** [comment]
@bpozdena , @arisliang 
> But I can't fix the client crash itself. Please try running the sync from CLI and report the crash on the onedrive client GitHub page.

There was a nasty timestamp bug introduced in v2,5.1 that has now been fixed with v2.5.2

**Comment by arisliang** [comment]
After upgrade to v2.5.2, the situation seems reversed. The message shows 'OneDrive is complete', but the button is not showing done.

![image](https://github.com/user-attachments/assets/dc593071-d03b-4361-9ee9-d07cb012cd32)

**Comment by bpozdena** [comment]
It's expected. The sync cycle runs every few minutes in the background.

**Comment by arisliang** [comment]
I remember there (v2.4.x) used to be a way to start the sync once and finish, without monitoring. Or is there?

**Comment by bpozdena** [comment]
Only the continuous monitor mode has been supported by the GUI. 

If you can briefly describe a use case for one time sync in the GUI, I can probably add it. I just can't imagine why it would be better then keeping it running continuously.

**Comment by abraunegg** [comment]
> I remember there (v2.4.x) used to be a way to start the sync once and finish, without monitoring. Or is there?

That capability *still* exists in the client - please read all the client documentation.

**Comment by arisliang** [comment]
> Only the continuous monitor mode has been supported by the GUI.
> 
> If you can briefly describe a use case for one time sync in the GUI, I can probably add it. I just can't imagine why it would be better then keeping it running continuously.

Perhaps some simple message like "OneDrive sync is complete, and monitoring", would be more explicit, than a stop button, which might lead to minor confusion, like:
- does the icon mean it's already stopped?
- or not stopped, but to click to stop? If so, why is it not stopped when the 'sync is complete'?

These are just minor confusions (especially for new users), but it can be clarified if just append 'monitoring' to the message.

**Comment by arisliang** [comment]
> > I remember there (v2.4.x) used to be a way to start the sync once and finish, without monitoring. Or is there?
> 
> That capability _still_ exists in the client - please read all the client documentation.

Yeah, that's probably how I got the impression the sync is one time operation, as I used the cli version at first. It is the default behavior of the cli client right? For monitoring in cli, you'd need to add the argument like `--monitor` or alike.

**Comment by abraunegg** [comment]
> Yeah, that's probably how I got the impression the sync is one time operation, as I used the cli version at first. It is the default behavior of the cli client right? For monitoring in cli, you'd need to add the argument like --monitor or alike.

Please read the documentation: 
* https://github.com/abraunegg/onedrive/blob/master/docs/usage.md#understanding-onedrive-client-for-linux-operational-modes
* https://github.com/abraunegg/onedrive/blob/master/docs/client-architecture.md#what-are-the-operational-modes-of-the-client
