### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by Bingo90** [bpozdena/OneDriveGUI#203]
Is there a way to disable logging? There's a lot of messages and this makes finding other logs pretty hard.

**Comment by bpozdena** [comment]
Logging of the GUI can be configured in the GUI settings:
![image](https://github.com/user-attachments/assets/9aa67903-9e26-487c-8af9-4c9e51dddadf)


But if you have a lot of files monitored by the onedrive client, you will always have a lot of log messages.

**Comment by Bingo90** [comment]
> Logging of the GUI can be configured in the GUI settings: ![image](https://private-user-images.githubusercontent.com/24818591/387187191-9aa67903-9e26-487c-8af9-4c9e51dddadf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5ODAzMzEsIm5iZiI6MTczMTk4MDAzMSwicGF0aCI6Ii8yNDgxODU5MS8zODcxODcxOTEtOWFhNjc5MDMtOWUyNi00ODdjLThhZjktNGM5ZTUxZGRkYWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDAxMzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NzExNWM0MTZlNDk2MWJlZTI2ZjBjMzU4NTBiMDk2NmU5Mzc5OGVhNWQ3NjdkMjZhM2QxOGVjZjcyMjkwNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZjvcaDdLhTjVej6uw5stGq3SWG4UZ3vvEWzw4gA9elg)
> 
> But if you have a lot of files monitored by the onedrive client, you will always have a lot of log messages.

I see. But is it possible to disable these messages too?

**Comment by bpozdena** [comment]
You can choose to not save the log, but the log message generation can't be disabled. Not sure why you'd want to see a blank terminal from app you start in terminal.
