### ISSUE TITLE
Feature Request: Display warning notice if 'onedrive' is not current / current version

### ISSUE THREAD

**Issue by abraunegg** [bpozdena/OneDriveGUI#21]
One aspect that I am trying to tackle is in the client itself, when it starts up, perform a check against the [github releases](https://github.com/abraunegg/onedrive/releases) and then display a warning note that the client is older than the current release.

It would be great, given that your code utilises the client underneath - if, somehow, in the GUI you present a warning flag | warning note that the client being used is older than the current released client.

This will help users keep their client version current - especially if they are running a package from a distribution that is not kept up-to-date.

**Comment by bpozdena** [comment]
Do you plan to do the check in the client itself and print a log message warning? This way I could just catch the log message.

If there is no such plan for the client, I will implement it in the GUI. Just want to avoid doing it twice.

**Comment by abraunegg** [comment]
@bpozdena 
Its on the whiteboard - but the issue is, that would be only implemented from version X - where as, you can be checking any version and providing feedback much earlier - so having this implemented independently I think would be a win-win situation.

**Comment by abraunegg** [comment]
That's AWESOME :) .. will help many folk using your GUI keep their client version updated - especially folk using packages on distributions that dont keep the client version up-to-date

**Comment by bpozdena** [comment]
Cool. I also changed the tooltip text color to white for better readability.

**Comment by abraunegg** [comment]
@bpozdena 
FYI - this is also added into the client itself - https://github.com/abraunegg/onedrive/pull/1862

When the client is obsolete, the following warning will be shown:
```
WARNING: Your onedrive client is obsolete and unsupported. Please upgrade your client version.
```

Now .. thats only going to work for folk who install the client from today (7/3/22) from source .. older clients / older builds will never get that code ..
