### ISSUE TITLE
Please support ondrive snap package, https://snapcraft.io/install/onedrive-cli/ubuntu

### ISSUE THREAD

**Issue by flyingosprey** [bpozdena/OneDriveGUI#210]
Why?

Because snap pakage is generally newer than "apt" package.

Currently, snap package is 2.5.3 while "apt" package is v2.4

Thanks.

**Comment by bpozdena** [comment]
I can only afford to maintain the AppImage package of the GUI. 

However you appear to be talking about the onedrive client, which is a different project. You should read its [install instructions](https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md).
