### ISSUE TITLE
Feature Request: Flatpak support

### ISSUE THREAD

**Issue by tazihad** [bpozdena/OneDriveGUI#22]
It would be awesome if you provide all of this inside flatpak including the abraunegg/onedrive

**Comment by bpozdena** [comment]
Packaging of the GUI is definitely planned once it is a bit more polished. Flatpak does sound like the best solution as I personally do not plan on maintaining multiple packaging solutions. 

I like the idea of including the client as well, just not sure how feasible it would be as I have no real experience with it. I will definitely look into it. 

Help would be welcome.

**Comment by KAMiKAZOW** [comment]
Some solution that works on Steam Deck without enabling developer mode would be appreciated, even if it were with reduced functionality. Flatpak is the preferred option but AppImage would also work. A client just needs to be integrated somehow because the root FS is read only by default.

**Comment by tazihad** [comment]
@KAMiKAZOW looks like [there's](https://github.com/bpozdena/OneDriveGUI/releases/latest) an appimage release

**Comment by KAMiKAZOW** [comment]
> @KAMiKAZOW looks like [there's](https://github.com/bpozdena/OneDriveGUI/releases/latest) an appimage release

It doesn't bundle the actual https://github.com/abraunegg/onedrive client which makes it non-functioning on SteamOS.

**Comment by bpozdena** [comment]
> It doesn't bundle the actual https://github.com/abraunegg/onedrive client which makes it non-functioning on SteamOS.

I can't bundle the client into the GUI AppImage, mostly due to dependency reasons. You could technically compile the client directly on the SteamDeck and then package it into the AppImage. You would also likely need to mount the `~/.config/` directories from some writable filesystem. Maybe also adjust path to the client executable in the GUI code. Not sure what else it would involve. I don't have a SteamDeck, so you are on your own.

**Comment by mbugni** [comment]
@bpozdena I created a [Flatpak prototipe](https://github.com/mbugni/OneDriveGUIFlatpak) for this project. The app starts and connects, the systray works (on KDE). The onedrive client is included, no additional dependencies are required.

I'm not a Python expert, but it seems there are some hard coded paths, like this:
```python
PROFILES_FILE = os.path.expanduser("~/.config/onedrive-gui/profiles")
```
Flatpak rely on XDG standards, like any decent DE. You should use some library like [xdg-base-dirs](https://pypi.org/project/xdg-base-dirs/) to manage configurations and data files, it should fit better with sandboxing.

Good luck

Snapshot:
![onedrive-gui-flatpak](https://github.com/bpozdena/OneDriveGUI/assets/14926724/6316045a-1c1b-4bc9-a68f-b5e24f472633)
