### ISSUE TITLE
Incompatibility with onedrive version < 2.4.14 or 2.4.16

### ISSUE THREAD

**Issue by backloop-biz** [bpozdena/OneDriveGUI#35]
Older version of onedrive available on Ubuntu repo (also 22.04) isn't compatible because of new config entry like: "operation_timeout".
Is it possibile to add a flag to write a config file compatible with older version?
Unfortunatelly if onedrive found entry not recognized in config file can't start.

Thanks

**Comment by bpozdena** [comment]
I do not plan to support legacy versions of the client. You really should update your onedrive client to the latest version. Just follow abrawnegg's detailed instructions: https://github.com/abraunegg/onedrive/blob/master/docs/ubuntu-package-install.md#distribution-ubuntu-2204
