### ISSUE TITLE
Settings window starts transparent

### ISSUE THREAD

**Issue by andreztz** [bpozdena/OneDriveGUI#38]
On the first startup, the settings window opens but shows nothing, and you have to click the "Show/Hide" button to get the GUI working again. Why start this window together with the main application? This seems unnecessary. 

![](https://i.imgur.com/KL2yQYd.png)

Thanks.

**Comment by bpozdena** [comment]
Please share the bellow details about your system:

Linux distribution and version:
Desktop environment and version:
Display Server (X11/Wayland):
Are you using Appimage or running the GUI from source?
Do you have "start minimized" feature enabled in the GUI?

**Comment by andreztz** [comment]
Linux distribution and version: Arch Linux
Desktop environment and version: Xfce4 4.16.4
Display Server (X11/Wayland): X11
Are you using Appimage or running the GUI from source? source
Do you have "start minimized" feature enabled in the GUI? yes

**Comment by bpozdena** [comment]
Thanks again @andreztz  for looking into it. Closing now with your PR https://github.com/bpozdena/OneDriveGUI/pull/44
