### ISSUE TITLE
[enhancement] Include GUI option to configure SharePoint-Shared-Libraries

### ISSUE THREAD

**Issue by jhonnym85** [bpozdena/OneDriveGUI#40]
Hi, 
Onedrive client includes the option to sync SharePoint-Shared-Libraries but it isn't possible to configure it on the GUI.
Here's the documentation [How to configure OneDrive SharePoint Shared Library sync.](https://github.com/abraunegg/onedrive/blob/master/docs/SharePoint-Shared-Libraries.md)
Is it possible to include this option?

**Comment by bpozdena** [comment]
I've never used this feature, but just based on the documentation, I should be able to add it into the setup wizard. I will just not have time to work on it in the next few weeks.

**Comment by bpozdena** [comment]
Hi @jhonnym85 & @Deldion ,

I've added support for the SharePoint Libraries into the GUI. Please test it from the v0.3 branch and let me know if there are any issues, further suggestions, etc.  

![image](https://user-images.githubusercontent.com/24818591/184706918-5b783b4e-476e-4d04-a7e3-2d8fda86c3da.png)

![image](https://user-images.githubusercontent.com/24818591/184707629-02ae964c-471e-4277-8ab3-38a24a2de1f8.png)

![image](https://user-images.githubusercontent.com/24818591/184708314-e514e50e-a48f-4f11-82a5-b43014bc5b5d.png)
