### ISSUE TITLE
Problem getting appimage working on Ubuntu 22.04.01

### ISSUE THREAD

**Issue by rogercreagh** [bpozdena/OneDriveGUI#53]
Ubuntu freshly upgraded from 20.04. By default on this machine appimage would not run. Since no other appimages had been installed it turned out that libfuse2 was not installed.

Perhaps worth including a note to run `sudo apt install libfuse2` if the appimage will not run even with permissions set correctly. Wasted a while tracking down the problem.

**Comment by bpozdena** [comment]
Maybe Canonical protecting Snaps? :-). Thanks for the suggestion @rogercreagh .
