### ISSUE TITLE
Installation from source instructions need updating

### ISSUE THREAD

**Issue by rogercreagh** [bpozdena/OneDriveGUI#54]
By default on Ubuntu 22.04.01 python3 is installed but python-is-python3 is not and nor is python3-pip so the commands as written in the instructions do not work. Suggest either change the instructions to say `python3 -m pip3 install -r requirements.txt` or add a note that on some systems the symlinks to get the python and pip commands working with python3 may need adding (which can be done with `sudo apt install python-is-python3 python-pip3` )

**Comment by bpozdena** [comment]
Not sure why are the symlinks missing on Ubuntu. Even official PIP documentation uses them. In any case, I updated the readme file to make it more explicit.
