### ISSUE TITLE
[Feature Request] Support for the OneDrive Client for Linux under Docker

### ISSUE THREAD

**Issue by Zeratoxx** [bpozdena/OneDriveGUI#57]
[This documentation](https://github.com/abraunegg/onedrive/blob/master/docs/Docker.md) explains pretty well how to set up the OneDrive Client for Linux by abraunegg using their Docker image.
However, the GUI does not find this way of installation.

**Comment by bpozdena** [comment]
I do not plan to add support for live monitoring of  Docker containers or systemd  services. I don't really even see any benefit for it. 

You can however still import your Onedrive config files from docker volumes into the GUI and use it for configuration changes.
