### ISSUE TITLE
Unknown key in config file: force_http_11

### ISSUE THREAD

**Issue by senorsmile** [bpozdena/OneDriveGUI#58]
I am trying this out for the first time.  I have the most recent version of abraunegg/onedrive installed: 
```
$ onedrive --version
onedrive v2.4.17
```

When I click on the play button, I see this error in the logs.

**Comment by senorsmile** [comment]
commenting out this in the config file gets it going, so it appears this just needs to be removed from this app?

**Comment by bpozdena** [comment]
Your onedrive client is too old and not supported by abraunegg. Please update to latest version 2.4.21

**Comment by senorsmile** [comment]
You're right!  Some how I had installed this a while ago and forgot about it.  The UI today was displaying a message explicitly telling me this, but I didn't see this a few days ago when I first raised the ticket.  Thanks for the quick response!
