### ISSUE TITLE
No module named 'PySide6.QtWebEngineWidgets'

### ISSUE THREAD

**Issue by emilbasv3** [bpozdena/OneDriveGUI#59]
Running the AppImage, produce the following error:

```
$ ./onedrivegui.appimage 
Traceback (most recent call last):
  File "/tmp/.mount_onedrilFR41C//usr/src/OneDriveGUI.py", line 65, in <module>
    from ui.ui_login import Ui_LoginWindow
  File "/tmp/.mount_onedrilFR41C/usr/src/ui/ui_login.py", line 18, in <module>
    from PySide6.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PySide6.QtWebEngineWidgets'
```

I've tried installing `PySide6` with no luck (`pip install PySide6`)

OS: Lubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-48-generic
Shell: bash 5.1.16
Python: 3.10.6

**Comment by bpozdena** [comment]
Looks like the temp dir was generated with lower case characters, which I've not seen on other distros. In any case, bellow is updated AppImage, which should technically fix this problem. 

[OneDriveGUI-1.0.1_fix59-x86_64.AppImage ](https://github.com/bpozdena/OneDriveGUI/releases/download/v1.0.1/OneDriveGUI-1.0.1_fix59-x86_64.AppImage)

Please confirm if this helped.

**Comment by emilbasv3** [comment]
Sorry for the late response, I can confirm, it is working now.
Thanks,
