### ISSUE TITLE
No notifications on errors

### ISSUE THREAD

**Issue by Tippon** [bpozdena/OneDriveGUI#60]
Thanks for making a GUI for onedrive, it's been really helpful :)

If you don't mind a suggestion though, it could do with error notifications. I installed it last night and got everything up and running, and it looked like my files were syncing. I left my laptop running for a few hours while I was doing other things, and came back to check, and onedrive had stopped after trying and failing to download a file three times. It stopped with the error 'Giving up on sync after three attempts'

>2022-Oct-15 22:11:46.6147135	Retry sync count: 1: Desktop/Games/3DMark2001 SE.lnk: No such file or directory
>2022-Oct-15 22:11:46.6147816	Applying changes of Path ID: 5CA1900F1F8E8E22!145
>2022-Oct-15 22:11:46.7283341	Updated Remaining Free Space: 130384932378
>2022-Oct-15 22:11:47.9748403	Processing 219 OneDrive items to ensure consistent local state due to sync_list being used
>2022-Oct-15 22:11:49.2147719	Processing 229 OneDrive items to ensure consistent local state due to sync_list being used
>2022-Oct-15 22:11:49.22893	Retry sync count: 2: Desktop/Games/3DMark2001 SE.lnk: No such file or directory
>2022-Oct-15 22:11:49.2290271	Applying changes of Path ID: 5CA1900F1F8E8E22!145
>2022-Oct-15 22:11:49.3423086	Updated Remaining Free Space: 130384932378
>2022-Oct-15 22:11:50.4348814	Processing 219 OneDrive items to ensure consistent local state due to sync_list being used
>2022-Oct-15 22:11:51.7048853	Processing 229 OneDrive items to ensure consistent local state due to sync_list being used
>2022-Oct-15 22:11:51.7175586	Giving up on sync after three attempts: Desktop/Games/3DMark2001 SE.lnk: No such file or directory

It would be nice to have an error message if something like this happens, so that we can check the issue and try to fix it, rather than having to manually check every now and then.

As an aside, it would also be nice if the logs could automatically split at a certain size. A 25MB log is hard to filter through, especially when you don't know what you're doing >.<

**Comment by bpozdena** [comment]
> it could do with error notifications. 

The error notifications are handled by OneDrive client itself. If you are not getting any system notifications even when sync starts/stops, ensure they are not disabled. You can check this even in the GUI under your profile settings > Logging tab > Notifications. You might also need to install libnotify ( see instructions [here](https://github.com/abraunegg/onedrive/blob/master/docs/INSTALL.md) )

In case the OneDrive client does still does not generate any notifications or does not generate them for all error events, please check on the [OneDrive client github page](https://github.com/abraunegg/onedrive). 


> it would also be nice if the logs could automatically split at a certain size. A 25MB log is hard to filter through, especially when you don't know what you're doing >

This is already supported in the GUI, just not based on log size, but based on time period. Perhaps you can open the GUI settings (Gear icon) and set 'log duration' to 1 hour and 'log backup count' to 24. 
If this is not convenient enough for your use case, let me know and I will add option to split the log based on file size as well.

**Comment by Tippon** [comment]
Thanks for replying :)

I've been getting the sync is starting notifications from the start, but nothing else. Strangely enough though, since last night I've been getting notifications for invalid names:

>2022-Oct-22 19:29:37.5229486	Skipping item - invalid name (Microsoft Naming Convention): ./Documents/desktop.ini

That's without changing anything.

I've just changed the log splitting options, but noticed that the log level is set to debug. Is that normal, or have I managed to change it without realising? (completely possible when I've got a six year old trying to get me to play Minecraft >.< )

**Comment by bpozdena** [comment]
Great, thanks for confirming. In case you see further issues with notification inconsistency, I'd suggest opening issue with the OneDrive client project.

Regarding the logging settings, your little gamer is not at fault :-). Debug level is the default for now - it will log all client and all GUI events. If you have multiple OneDrive accounts, all logs will be combined into a single file.

If you want to have separate log files for your individual OneDrive accounts,  you can enable [logging from the OneDrive client directly](https://github.com/abraunegg/onedrive/blob/master/docs/USAGE.md#client-activity-log) (GUI under your profile settings > Logging tab).

**Comment by Tippon** [comment]
> > it would also be nice if the logs could automatically split at a certain size. A 25MB log is hard to filter through, especially when you don't know what you're doing >
> 
> This is already supported in the GUI, just not based on log size, but based on time period. Perhaps you can open the GUI settings (Gear icon) and set 'log duration' to 1 hour and 'log backup count' to 24. If this is not convenient enough for your use case, let me know and I will add option to split the log based on file size as well.

Apologies, I am a donut >.<

It's the Onedrive logs that are not splitting, not your logs. I confused the two in the settings, and thought it was the GUI logs that were getting massive.
