### ISSUE TITLE
can't login in as education account

### ISSUE THREAD

**Issue by LiBai3121** [bpozdena/OneDriveGUI#62]
I creat the office 365 account by my university mail. I have login in onedrive successeful in the Windows 10 OS and upload my document. I want to download the document from onedrive in  the Linux OS but I failed when login with the OneDriveGUI.
details: I click the url button and login in the website but the returned url is "https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_client&error_description=AADSTS650051%3a+Using+application+%27OneDrive+Client+for+Linux%27+is+currently+not+supported+for+your+organization+stu.xmu.edu.cn+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+stu.xmu.edu.cn+before+the+application+OneDrive+Client+for+Linux+can+be+provisioned.%0d%0aTrace+ID%3a+f750a2d6-bb79-4fc8-a042-8e33be323200%0d%0aCorrelation+ID%3a+0fc1b326-df83-4d24-b5c0-f131cd6ea4ca%0d%0aTimestamp%3a+2022-10-23+12%3a41%3a04Z". So the "login" button isn't available for clicking when I cope the returned url to the GUI.
![2022-10-23_20-44](https://user-images.githubusercontent.com/67818374/197393050-e02b1906-61f0-411c-a28a-2528a78675f1.png)

Is there anybody can help me?

**Comment by bpozdena** [comment]
Please contact your administrator to properly claim the domain ownership . The solution is in the response URL:

An administrator needs to claim ownership of the company by DNS validation of stu.xmu.edu.cn before the application OneDrive Client for Linux can be provisioned.

This was already discussed on the [OneDrive client page](https://github.com/abraunegg/onedrive/issues/19).
