### ISSUE TITLE
Could not load the Qt platform plugin "xcb" in "" even though it was found on Debian

### ISSUE THREAD

**Issue by Palmeta** [bpozdena/OneDriveGUI#66]
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Am getting this error constantly when i try to execute.

**Comment by bpozdena** [comment]
How did you install OneDriveGUI? AUR, AppImage or are you running it from source? 

What's your Linux distribution name and version?

What desktop environment do you use?

X11 or Wayland?



Also please check for clues in previous similar issue #47 .

**Comment by bpozdena** [comment]
Closing for lack of details/response.

**Comment by y8s** [comment]
Rather than create this again, I'm having this same issue.

Using XFCE4 in a Debian 11 LXC on proxmox. XFCE4 was installed after the container was up and running
I'm running under a user account with sudo privileges as needed.

It is unprivileged with FUSE enabled.

I've tried running from v1.0.1 source and running from the `OneDriveGUI-1.0.1_fix59-x86_64.AppImage` and both show the same error. I've installed all libxcb* packages with no positive results.

note that I have got the service running fine in another install in linux mint. 

full output:

```
username@onedrive:~/OneDriveGUI$ ./OneDriveGUI-1.0.1_fix59-x86_64.AppImage 
2023-02-10 21:30:29,956 [OneDriveGUI.py:2789][fn=get_installed_client_version][DEBUG] - [GUI] Installed client version is 2423
2023-02-10 21:30:29,960 [OneDriveGUI.py:2824][fn=create_global_config][DEBUG] - [GUI] - loading default config {'onedrive': {'sync_dir': '"~/OneDrive"', 'skip_file': '"~*|.~*|*.tmp"', 'monitor_interval': '"300"', 'skip_dir': '""', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"false"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"'}}
2023-02-10 21:30:29,960 [OneDriveGUI.py:2863][fn=create_global_config][DEBUG] - [GUI]{}
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
```

**Comment by bpozdena** [comment]
Before we get into debugging, can you please ensure all bellow XCB dependencies are installed on your system?


Here is a list from clean Debian 11 VM with KDE, where OneDriveGUI works fine.: 
```
apt list --installed | grep xcb    

libx11-xcb1/stable,now 2:1.7.2-1 amd64 [installed,automatic]
libxcb-composite0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-cursor0/stable,now 0.1.1-4 amd64 [installed,automatic]
libxcb-damage0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-dpms0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-dri2-0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-dri3-0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-glx0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-icccm4/stable,now 0.4.1-1.1 amd64 [installed,automatic]
libxcb-image0/stable,now 0.4.0-1+b3 amd64 [installed,automatic]
libxcb-keysyms1/stable,now 0.4.0-1+b2 amd64 [installed,automatic]
libxcb-present0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-randr0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-record0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-render-util0/stable,now 0.3.9-1+b1 amd64 [installed,automatic]
libxcb-render0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-res0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-shape0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-shm0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-sync1/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-util1/stable,now 0.4.0-1+b1 amd64 [installed,automatic]
libxcb-xfixes0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-xinerama0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-xinput0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-xkb1/stable,now 1.14-3 amd64 [installed,automatic]
libxcb-xv0/stable,now 1.14-3 amd64 [installed,automatic]
libxcb1/stable,now 1.14-3 amd64 [installed,automatic]

```

**Comment by bpozdena** [comment]
OK, I've setup Debian 11 LXC, did some debugging and I was able to fix it by installing the bellow dependencies:

`apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0`

This would mean the AppImage is missing only 'libxkbcommon-x11-0'. 

Unfortunately I could only test by running the GUI from source as I did not manage to load the fuse kernel module. If you can share the exact steps to get fuse2 working on the Debian LXE, that would help me verify the fix for AppImage.

**Comment by bpozdena** [comment]
Please try this [ OneDriveGUI-1.0.1_fix66-x86_64.AppImage ](https://github.com/bpozdena/OneDriveGUI/releases/download/v1.0.1/OneDriveGUI-1.0.1_fix66-x86_64.AppImage) with the added libxkbcommon-x11-0  dependency.

**Comment by y8s** [comment]
libxkbcommon-x11-0 appears to be the missing package. I installed that and the python command worked.

I also tried the above fix66 appimage and it worked as well.

(though to be fair, I tried it after installing the above package so who knows. Now the fix59 version works too)

Thanks for the help!

**Comment by bpozdena** [comment]
Thanks for the confirmation. I'm glad it worked.
