### ISSUE TITLE
is there anyway to let docker have a webui?

### ISSUE THREAD

**Issue by penwong** [bpozdena/OneDriveGUI#70]
hi,i'm new to linnux，recently using unraid  to build a NAS , so i extremely want a GUI to let me know the onedrive status , but i dont have a desktop env .  just asking , thanks

**Comment by bpozdena** [comment]
Hi,
sorry this project will not help with your needs. 

Maybe you can check out another project [docker-onedrive-webui](https://github.com/tanaga9/docker-onedrive-webui).  It was once mentioned on the [OneDrive Client page](https://github.com/abraunegg/onedrive/issues/1668). 

But if you simply want to monitor the service status, there are countless other tools for that.
