### ISSUE TITLE
Why in Python instead of D?

### ISSUE THREAD

**Issue by zigomi** [bpozdena/OneDriveGUI#75]
Why is it in Python instead of Dlang?

**Comment by bpozdena** [comment]
Because.... I don't know D. 

NOTE: Please put questions into the 'Discussions' section next time.

**Comment by zigomi** [comment]
Oh, I've confused you with this guy - [abraunegg/onedrive](https://github.com/abraunegg/onedrive) :) He refers to this repo from his.

**Comment by daayve** [comment]
Zigomi, I know the answer...  :)
