### ISSUE TITLE
The client blocks freeze when trying suspend/hibernate 

### ISSUE THREAD

**Issue by j054n** [bpozdena/OneDriveGUI#79]
I have installed on Debian 11 OneDriveGUI-1.0.1_fix59-x86_64.AppImage following the instructions buit when I try suspend/hibernate computer fails. Debug mesages:
[lun ene 30 12:26:43 2023] Freezing user space processes ...
[lun ene 30 12:27:03 2023] Freezing of tasks failed after 20.005 seconds (1 tasks refusing to freeze, wq_busy=0):
[lun ene 30 12:27:03 2023] task:onedrive        state:D stack:    0 pid: 2488 ppid:  2487 flags:0x00004004
[lun ene 30 12:27:03 2023] Call Trace:
[lun ene 30 12:27:03 2023]  __schedule+0x282/0x870
[lun ene 30 12:27:03 2023]  schedule+0x46/0xb0

Any solution?
Thnaks in advance.

**Comment by bpozdena** [comment]
I've never seen this issue on systems that I suspend. 

Based on ` task:onedrive state:D ` I'm also not sure it if is related to the GUI itself.


Can you please test sleep/hibernation while NOT running OneDriveGUI, but running just the [OneDrive client](https://github.com/abraunegg/onedrive) in CLI or as service?

If the issue happens only when OneDriveGUI is used, can you reproduce it by [running if from source](https://github.com/bpozdena/OneDriveGUI#running-from-source)?

**Comment by j054n** [comment]
When I run the OneDrive client as service/cli sleep/hibernation is successful

**Comment by j054n** [comment]
![B39AE2AC-8F5C-41C6-85D5-6396E77D2606](https://user-images.githubusercontent.com/3328208/215494241-a919446b-c91b-4fe3-8738-3e78a6f6e058.jpeg)

**Comment by bpozdena** [comment]
Can you reproduce it by [running if from source](https://github.com/bpozdena/OneDriveGUI#running-from-source)? I'm trying to see if the issue is specific to AppImage/FUSE2.

**Comment by j054n** [comment]
I have tested from source also and the same result, I think it can be related to the permissions taken by user when executes OneDrive daemon from python3 or similar

**Comment by bpozdena** [comment]
I have not been able to reproduce it on freshly installed Debian 11. Both hibernation and sleep worked fine. I will need more details from you. 

Can you share the trace from when you run the GUI directly from source? 

Also, do you have the same issue with other AppImages or other Python projects?
