### ISSUE TITLE
No GUI & No Tray Icon

### ISSUE THREAD

**Issue by zz0rk** [bpozdena/OneDriveGUI#84]
OS: Debian 11
OneDriveGUI: OneDriveGUI-1.0.2-x86_64
Python: Python 3.9.2

1) Open OneDriveGUI-1.0.2-x86_64
2) Gnome notification is reporting OneDrive monitoring is initializing.
3) No tray icon and no GUI for OneDrive
4) Check onedrive-gui.log. OneDrive is running and synching. No errors.

Thank you

**Comment by zz0rk** [comment]
This behavior was caused by Gnome shell extension gnome-shell-extension-appindicator.
Upgrading to v48 resolved the issue.
I am curious though why OneDriveGUI is depended on tray icon integration in order to function properly.
Thank you

**Comment by bpozdena** [comment]
Thanks for confirming the root cause. 

The expected behavior is that OneDriveGUI will minimize to tray only when it is available, otherwise it will minimize to dock/taskbar.

**Comment by bpozdena** [comment]
This could happen if your system tray extension is enabled but does not work correctly. I don't think I can identify bugs in gnome extensions. 

In any case, if you disable or uninstall the system tray extension, OneDriveGUI should just remain in the dock. Let me know if this is not true anymore and I will take a closer look at it.

**Comment by zz0rk** [comment]
I can confirm that the app behaves as you described above. My issues where caused because a) the tray extension was faulty and b) I had the dash dock disabled and therefore I had no access to GUI. Thank you :smile:
