### ISSUE TITLE
Autostart on system login

### ISSUE THREAD

**Issue by manueldeprada** [bpozdena/OneDriveGUI#88]
I did not see it in the documentation...

Is there an easy or recommended way to autostart OneDriveGUI after login?

Excellent work, thanks for this application!!

**Comment by bpozdena** [comment]
This will depend on your distribution and desktop environment. Most distros come with some kind of autostart application where you can add the AppImage. In some distros you need to make a link to to the AppImage into the user autostart directory.

Just search how to autostart apps in your distro.
