### ISSUE TITLE
Support for arm64 or aarch64

### ISSUE THREAD

**Issue by afzl-wtu** [bpozdena/OneDriveGUI#90]
Can you add support for these linux versions?

**Comment by bpozdena** [comment]
Sorry, it's currently not planned as I don't have any Arm HW for testing.

**Comment by afzl-wtu** [comment]
> Sorry, it's currently not planned as I don't have any Arm HW for testing.

if you want I can test it

**Comment by Tianbawen** [comment]
I need aarch64 please
