### ISSUE TITLE
How do you compile your .ui files?

### ISSUE THREAD

**Issue by JL102** [bpozdena/OneDriveGUI#91]
Hi,

I'm looking to contribute to OneDriveGUI, and the first thing I'd like to contribute is to make the UI a bit more smooth and comfortable. I downloaded Qt Creator and I was able to open & edit the .ui files, but when I used pyuic5 to compile them, the output is VERY different from what it was originally.

Here's the command I entered:
```
pyuic5 process_status_page.ui -o ui_process_status_page.py
```
pyuic5 version:
```
Python User Interface Compiler 5.15.7 for Qt version 5.15.2
```

and here's the diff:
![image](https://user-images.githubusercontent.com/11487870/229619427-b14442b1-403e-4bb2-98a3-0c61e1ca9c09.png)

All I tweaked so far was a few numbers and tooltips. What process do you use to compile the .ui files into .py? I'd like to contribute but I obviously would not want to commit changes as drastic as this.

**Comment by JL102** [comment]
I figured out that I can use `pyside6-uic` to compile the files. Do you have a Qt studio project file that you use to build your .ui files, or do you use `pysize6-uic` in the command line like I did?

**Comment by bpozdena** [comment]
Hi @JL102 ,

Please use QT Designer, which you can find in wherever you PIP installed PySide6==6.2.2.1 . Bellow is example when Pyside6 is installed in virtual environment `venv`.
`../OneDriveGUI/venv/lib64/python3.10/site-packages/PySide6/designer`

Once your virtual environment is activated, command `pyside6-uic --version` should output `uic 6.2.2`. 

To compile the Ui file into Py file, you can use command `pyside6-uic mainwindow.ui > ui_mainwindow.py`

**Comment by JL102** [comment]
Nice, thanks! I didn't realize that Qt Designer was included in the python packages.
