### ISSUE TITLE
[Request] Keep a database of the OneDrive operation history, so that it stays visible after re-launching the app

### ISSUE THREAD

**Issue by JL102** [bpozdena/OneDriveGUI#96]
Hi,

It would be helpful if there was a way to keep the operation history persistent across app re-launches, so that the user can view the sync history even after the app was closed and re-opened. If this is implemented, it would probably make sense to keep a hard cap on either the number of operations saved or the amount of time (e.g. 30 days of history), but in any case it would be really nice to have.

**Comment by bpozdena** [comment]
It's currently not supported. I think even the Windows client does not keep the history.

Implementing it would be tricky in that there would be errors or missing file icons if some files were moved/deleted between the GUI restarts. Qt needs access to the files to display icons etc, file path, etc.

We would probably also have to show the time when the event happened, which would need completely new layout, etc.

I'd say it's too much work. I'll close this for now. 

You can use the log files to see past events. You can even configure the log retention in the GUI settings.

**Comment by JL102** [comment]
> We would probably also have to show the time when the event happened, which would need completely new layout, etc.

@bpozdena Funnily enough, I was working on just that earlier today, right after I opened that issue 😅 - There was space to the right of the file name, which I think is perfect for a timestamp.

I tried to turn it into a "5 minutes ago" / "2 hours ago" / "Just now" timestamp, but it would require updating the widgets' text as you scroll through them, but it would require a way to fire some kind of event as a given TaskList widget becomes visible as you scroll (i.e., updating its timestamp once it appears again in the list), and I couldn't find a way to do that.
![screenshot](https://user-images.githubusercontent.com/11487870/229969621-20e32782-bd64-41cb-8715-76c36696a6be.png)
